### ISSUE TITLE
Ambiguous license release

### ISSUE THREAD

**Issue by Stefan-Endres** [naught101/sobol_seq#11]
The README.md says that the code is published with a MIT license.

However, the main file in sobol_seq/sobol_seq.py contains a "GNU LGPL license".

Could we please get clarification on if the code is indeed MIT since we want to include this code in a library that must contain only pure MIT licensed code. However, LGPL requires that we keep in the license comments in the main .py file.

**Comment by apaleyes** [comment]
We are concerned about the same issue. Can some please confirm if this is a mistake or does this file have to be LGPL?

**Comment by naught101** [comment]
Yes, it looks like this was a mistake/ill-informed decision (I can't remember) on my part a few years ago.

Fixed in 6ac1799

**Comment by Stefan-Endres** [comment]
Thank you very much.

**Comment by apaleyes** [comment]
Thanks a lot, that was a very quick and timely update.
