### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by comatrion** [naught101/sobol_seq#12]
The [README](https://github.com/naught101/sobol_seq/blob/master/README.md#usage) promises **i4_sobol_generate_standard_normal** however:

```
In [1]: import sobol_seq

In [2]: sobol_seq.i4_sobol_generate_standard_normal(4,5)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-0a650e5011fc> in <module>()
----> 1 sobol_seq.i4_sobol_generate_standard_normal(4,5)

AttributeError: 'module' object has no attribute 'i4_sobol_generate_standard_normal'
```

**Comment by naught101** [comment]
Huh? The readme pretty clearly reads

`sobol_seq.i4_sobol_generate_std_normal`, not 

`sobol_seq.i4_sobol_generate_standard_normal`.

Closing as a non-bug. Feel free to re-open if I've missed something.
