### ISSUE TITLE
Unable to install sobol_seq on conda for python 3.6.3

### ISSUE THREAD

**Issue by shihabkhan1** [naught101/sobol_seq#13]
I am trying to install sobol_seq using conda `conda install -c naught101 sobol_seq ` and I am getting the following error
![sobol_seq_error](https://user-images.githubusercontent.com/24490783/34510939-0f572cb0-f07e-11e7-9f20-b6a0a6f3f054.png)
I've read on some forums that a python downgrade might be required.

By using the other command, `conda install -c https://conda.binstar.org/naught101 sobol_seq`, I am getting the same error.

Can someone please help? I'm new to python.

**Comment by naught101** [comment]
You can install using pip:

`pip install git+https://github.com/naught101/sobol_seq.git`

**Comment by shihabkhan1** [comment]
Thanks a lot!
