### ISSUE TITLE
How can I install the package?

### ISSUE THREAD

**Issue by alinamadchian** [naught101/sobol_seq#17]
I am using Anaconda in windows
when I try to run the setup.py file in Anaconda environment it gives me the error:

**An exception has occurred, use %tb to see the full traceback.

SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

C:\Python\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2870: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)**

**Comment by naught101** [comment]
Install from conda directly, using the command in the readme. If that doesn't work, please paste the error message.

Otherwise, you can also try `pip install` from within the package directory.

**Comment by naught101** [comment]
Closing in favour of #18
