### ISSUE TITLE
PYPI

### ISSUE THREAD

**Issue by CnrLwlss** [naught101/sobol_seq#2]
This package is really useful.  I would like to make my Colonyzer package (available on PYPI) depend on sobol_seq, so that my users can pip install in one go.  I have added a dependency on "sobol", which has been working well, however, I notice that has been generated from a fork of this repo and that the older fork isn't PY3 ready.  Would you mind submitting this package to PYPI?  Or would you mind if I did it?  Or could we ask the current maintainers of the PYPI package if we could update it?

**Comment by naught101** [comment]
I'm not really that interested in pypi... I think conda is the way of the future, and I've pushed the package to the binstar repo.

That said, I am happy for you to manage a pypi package for this package, or ask the current maintainer, which ever is easier. If you need any modifications to the package to make either of those easier, let me know.

**Comment by CnrLwlss** [comment]
That sounds great, thanks!  I've submitted a pull request with some modifications for PYPI.  

I'd be interested to know what you prefer about conda?

Until recently, I have thought that package management in Python was pretty broken.  I have always found it difficult to explain to users that they had to install python, then easy_install pip then pip install Colonyzer.  Recent versions of python3 include pip by default, removing a step, making installation much smoother.  

I will get in touch with Victor Ng.

**Comment by naught101** [comment]
https://github.com/naught101/sobol_seq/pull/3 merged

Conda is better than pip because it deals with compiled packages, which means you don't have to screw around waiting for packages to compile. It also provides virtual environments, and packages can be shared between environments, without re-compiling. I think the virtual environment setup is neater than virtualenv too.
