### ISSUE TITLE
Anaconda Cloud

### ISSUE THREAD

**Issue by allefeld** [naught101/sobol_seq#21]
Could you make the last version of the library available via Anaconda Cloud?

<https://anaconda.org/naught101/sobol_seq> still says version 0.1

And would you consider submitting it to conda-forge, instead of using your own channel?

Thanks!

**Comment by naught101** [comment]
You're probably right that a conda-forge package would be better, but I don't really have the time to make a recipe and a PR for it. Feel free to submit your own. I'll be happy to update the docs here to reflect that.

**Comment by allefeld** [comment]
I understand if you don't have time to move to conda-forge. But maybe you can update the package on your own conda channel? I assume you must already have the recipe for that?

**Comment by naught101** [comment]
I don't think I do right now. I have had a laptop stolen since then, and I may have a copy on a backup some where, but it's probably easier to just write one from scratch, especially considering that I looks like conda-forge has some other requirements than what I built my package with.

**Comment by naught101** [comment]
I'm giving up maintenance of this module in favour of Scipy, see discussion at https://github.com/naught101/sobol_seq/issues/15

So it doesn't make sense to add this to Anaconda anymore.
