### ISSUE TITLE
sobol-seq

### ISSUE THREAD

**Issue by keithbriggs** [naught101/sobol_seq#22]
This installed ok with pip, but it says:

> Successfully built sobol-seq
> Installing collected packages: sobol-seq
> Successfully installed sobol-seq-0.2.0

If the name of the package is sobol_seq, why does it call it sobol-seq?

**Comment by naught101** [comment]
Looks like the package name on pypi is wrong. It doesn't really matter that much though. You're still gonna need to use `import sobol_seq`. I don't think this is worth changing.
