### ISSUE TITLE
broken link in README

### ISSUE THREAD

**Issue by keithbriggs** [naught101/sobol_seq#24]
> Scipy now has an implementation of a Sobol sequence generator, which is more feature complete than this one. You can see the documentation here: https://docs.scipy.org/doc/scipy/reference/reference/generated/scipy.stats.qmc.Sobol.html

```
Not Found

The requested URL /doc/scipy-1.8.0/html-scipyorg/reference/reference/generated/scipy.stats.qmc.Sobol.html was not found on this server.
Apache/2.4.39 (Ubuntu) Server at docs.scipy.org Port 443
```

**Comment by keithbriggs** [comment]
Should be: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.qmc.Sobol.html.

**Comment by naught101** [comment]
fixed
