### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bstemper** [naught101/sobol_seq#6]
Hey,

I understand that you mean this code to be open-source but could you maybe add a license to make it 'waterproof'? 

http://choosealicense.com

Thanks!

**Comment by naught101** [comment]
The majority of the code is from http://people.sc.fsu.edu/%7Ejburkardt/py_src/sobol/sobol.html which mentions the MIT license. Feel free to create a pull request with appropriate changes.

On 17 May 2016 7:43:48 PM AEST, Benjamin Stemper notifications@github.com wrote:

> Hey,
> 
> I understand that you mean this code to be open-source but could you
> maybe add a license to make it 'waterproof'? 
> 
> http://choosealicense.com
> 
> Thanks!
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/naught101/sobol_seq/issues/6

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bstemper** [comment]
#7 Okay, done (to the best of my knowledge!).

**Comment by naught101** [comment]
See also fix in https://github.com/naught101/sobol_seq/issues/11
